### ISSUE TITLE
Addition of support for block submission mechanism

### ISSUE THREAD

**Issue by jbunce** [omgnetwork/elixir-omg#1092]
As an operator of the Childchain service
I wish to be able to HTTPS POST the Merkle root to the root chain
So keys are not held in an application/node

**Comment by paulperegud** [comment]
Will secure cluster download and validate the block before submitting commitment to Ethereum? If not, it's acting in "garbage in garbage out" mode. I.e. it's enough to compromise childchain service to submit a block that gives hacker all of the chain funds, causing mass exit.

**Comment by pnowosie** [comment]
Some thoughts after our call:
- attacker is still incentivized to hack Childchain counting on not everyone will managed to exit (due to protocol-unrelated reasons: lost key, lack of experience)
- there is no risk that attacker would be able to call secure cluster hash-publishing endpoint
- it still makes sense to have it (without validation) because Childchain (or node) should not deal with keys
- we agreed we can postpone it after the mainnet launch

@paulperegud elaborated on his idea of validation
- Childchain notifies trough some streaming channel that new block is ready (nothing is published on Ethereum yet)
- Interested parties can grab the block (e.g. Watchers, BlockExporers)
- Secure cluster fetches the block validates it with its Watcher and if validation is successful publishes hash on Ethereum

(CC @jbunce @thec00n @paulperegud feel free to update this post)

**Comment by InoMurko** [comment]
@jbunce is this a mainnet blocker? seems security related ... cc @thec00n 

PS: Somehow related to @paulperegud comment https://github.com/omisego/elixir-omg/issues/1202

**Comment by thec00n** [comment]
Yeah definitely a main net blocker from a security perspective. This is related to the Vault project. CC @jbunce

**Comment by unnawut** [comment]
being taken care of as part of the vault project plus not much info to carry over in this issue so this tracking on elixir-omg is no longer necessary
