### ISSUE TITLE
Watcher Info API: /deposit.all

### ISSUE THREAD

**Issue by thec00n** [omgnetwork/elixir-omg#1133]
As a user I would like to query the Watcher API to retrieve the deposit tx.

The smart contracts emit `DepositCreated` and after a certain number of blocks the tx is included in the child chain. How do I retrieve that tx? I have not found a way how this is currently done.

**Comment by pdobacz** [comment]
Thank you!

I think this only i represented by a deposit UTXO in the UTXO set, that should be retrievable using Watcher APIs.

This is something in between
 - remnants from times when there wasn't a `deposit tx` formulated, when a deposit was done (it was a magic UTXO)
 - being able to not deal with those deposit blocks - but this argument is weak, I'm inviting the possibility to treat deposit blocks as blocks everywhere consistently, but this would require some careful thinking

> How do I retrieve that tx?

Internally, this `deposit tx` is reconstructable from the UTXO that the deposit adds, and this is what we're doing now.

Externally, I think you should only ever need the UTXO, which is available in the Watcher. Is there an "external" use case for the `deposit tx`?

**Comment by thec00n** [comment]
Thanks for clarifying @pdobacz.

`Internally, this deposit tx is reconstructable from the UTXO that the deposit adds, and this is what we're doing now.`

How is this done? Does the child monitor for `DepositCreated` events from the contracts and then reconstructs the UTXO position from `blknum` and tx index and output index are assumed to be always zero? 

`Externally, I think you should only ever need the UTXO, which is available in the Watcher. Is there an "external" use case for the deposit tx?`
I was just surprised that they would not show up in the tx. Now that I think about it makes sense. They are not actually real tx, more like an initial state that is backed up by the contracts. I just looked at the `account.get_utxos` and there you can see the deposits based on the the block numbering.

**Comment by thec00n** [comment]
I do have followup questions:
- How does a client exit a deposit tx? It needs to RLP encode a tx, so does it reconstruct the tx from the UTXO info?
- How does a client generate the inclusion proof for a deposit tx?
- Does the child chain generate a block for a deposit tx?

**Comment by jrhite** [comment]
A couple of notes:

- a deposit from rootchain to childchain does not create a plasma transaction. It only creates an UTXO.
- i don't know much about the RLP encoding of a tx, but since there is no tx I'm not sure how this works. The UTXO created by the deposit can be exited by startStandardExit().
- about inclusion of proof i'm not sure since there is no tx
- the childchain will not generate a block for a deposit, since only a utxo is created and not a tx.

**Comment by pdobacz** [comment]
> `Internally, this deposit tx is reconstructable from the UTXO that the deposit adds, and this is what we're doing now.`
> 
> How is this done? Does the child monitor for `DepositCreated` events from the contracts and then reconstructs the UTXO position from `blknum` and tx index and output index are assumed to be always zero?

Yes, like that!

> How does a client exit a deposit tx? It needs to RLP encode a tx, so does it reconstruct the tx from the UTXO info?

Yep

> How does a client generate the inclusion proof for a deposit tx?

The Watcher (not the client) takes care of it. It produces a 1-tx block and uses that to get the inclusion proof

> Does the child chain generate a block for a deposit tx?

Nope

This :point_up: is all current implementation. I would some see benefits from treating deposit txs as retrievable txs and deposit blocks as retrievable blocks, but this would require something like a "shift of paradigm" and some thinking/coding.

**Comment by jrhite** [comment]
☝️ what @pdobacz , please ignore my previous notes. I was misunderstanding the difference between what lives in Watcher's postgres DB vs what is happening in the contracts.

**Comment by unnawut** [comment]
We also need this info for the block explorer (https://github.com/omisego/blockexplorer/issues/74<sup>1</sup>). Most straightforward would be this I think:

**Scope:** Watcher Informational API

**Endpoint:** `/deposit.all`

**Request:**

```json
{
  "address": "0xf876154263cF61E15e84695096cFdCb5ceEd8D86"
}
```

Request params:
- `address` can be omitted to return an unfiltered list

**Response:**
```json
{
  "success": true,
  "data": [
    {
      "eth_hash": "0x2733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981f",
      "amount": 1000,
      "currency": "0x08f0f4E4049218C8BF0978e4001b4FB85bC97C3C",
      "owner": "0xf876154263cF61E15e84695096cFdCb5ceEd8D86",
      "utxo_pos": 68290000000000000,
      "timestamp": "1234567981"
    },
    {
      "eth_hash": "0x9154ed3a7609a2f1ff981f2733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c",
      "amount": 2000,
      "currency": "0x08f0f4E4049218C8BF0978e4001b4FB85bC97C3C",
      "owner": "0xf876154263cF61E15e84695096cFdCb5ceEd8D86",
      "utxo_pos": 68290000000000001,
      "timestamp": "1234568000"
    }
  ]
}
```

**Watcher Info DB usage:**

- [Existing] `ethevents.event_type` --> to filter for deposits
- [Existing] `ethevents_txoutputs.root_chain_txhash_event` --> eth_hash
- [Existing] `txoutputs.amount` --> amount
- [Existing] `txoutputs.currency` --> currency
- [Existing] `txoutputs.owner` --> owner
- [Add] `txoutputs.utxo_pos` --> utxo_pos
- [Add] `ethevents.timestamp` --> timestamp

Would this work? @thec00n @pdobacz 

Another approach would be `/event.all` with request param `{type: deposit}`, but then we need to generalize the response params and drop specific data e.g. deposit's utxo, etc...

---
<sup>1</sup> Unfortunately the design url is lost due to domain migration, we're recovering it but will take some time.

**Comment by unnawut** [comment]
☝️ A following endpoint would be `/exit.all` in watcher info API.

**Comment by jrhite** [comment]
For reference...

2 ways to determine if a UTXO is a deposit:
1. join the `txoutputs` <-> `txoutputs_ethevents` <-> `ethevents` and check that `event_type == 'deposit'`
2. call `OMG.Utxo.Position.is_deposit(Utxo.position(blknum, txindex, oindex))`
