### ISSUE TITLE
auto sync master and master-v2

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/elixir-omg#1603]
Probably reuse the GH action setup in plasma-contracts and plasma-contract-private

**Comment by souradeep-das** [comment]
What should be the ideal way to merge into master-v2?

If we squash-and-merge the commits apparently add up every-time (since there is no reference to this older commits on master-v2)

For instance, the successive pull requests will look like this-

1st PR
<img width="750" alt="Screenshot 2020-06-30 at 1 25 45 PM" src="https://user-images.githubusercontent.com/26090752/86100788-f1c1d080-bad6-11ea-996e-783a5adcad5d.png">
 
2nd PR
<img width="569" alt="Screenshot 2020-06-30 at 1 28 43 PM" src="https://user-images.githubusercontent.com/26090752/86100859-07cf9100-bad7-11ea-83a1-7f35ab5a5789.png">

3rd PR
<img width="652" alt="Screenshot 2020-06-30 at 1 30 53 PM" src="https://user-images.githubusercontent.com/26090752/86100886-10c06280-bad7-11ea-850d-1103e99ebd83.png">
