### ISSUE TITLE
Add Log Status For Stdout

### ISSUE THREAD

**Issue by kendricktan** [omgnetwork/elixir-omg#997]
Currently everything being logged to datadog is of status `Info`. This makes it hard to investigate / traceback where the error originated in datadog.

It would be nice if we incorporated DD's logging guideline to differentiate between `Info`, `Warning` and `Error` stdout. - https://docs.datadoghq.com/logs/faq/why-do-my-logs-show-up-with-an-info-status-even-for-warnings-or-errors/

**Comment by InoMurko** [comment]
As it seems this could be solved by defining a grok parser https://docs.datadoghq.com/logs/processing/parsing/?tab=matcher

Do you see this option in your Datadog view? I might not have enough rights to configure this. But each log entry has [*level*] defined... so that could be our status.

But since we gather logs from Stdout, that's our only option. If that doesn't work be ought to go to JSON logs.

**Comment by InoMurko** [comment]
@kendricktan whats up with this? it would be cool to have!

**Comment by unnawut** [comment]
done

![image](https://user-images.githubusercontent.com/921194/84069693-1f928880-a9f5-11ea-9df3-62230098f33e.png)
